Sprint 15 сложные коллекции и core data
snowsergo/tracker pull request #1
Opened 2023-03-21 20:32 UTC by snowsergo

2023-03-22 21:37 UTC, IBDesignable requested changes
1. Неверно работает фетч запрос категорий. После того как приложение сохраняет категорию, при повторном запросе – она должна появляться. При этом после перезагрузки - категории снова видны. Значит контексты после сохранения не синхронизируются.
![RocketSim_Recording_iPhone_14_Pro_2023-03-22_23 33 10](https://user-images.githubusercontent.com/121577115/227043901-7afe10b9-4874-4524-9090-fda66f150611.gif)

2. Добавление новых записей о выполненых привычках и событиях должны инкрементировать счетчик выполнненых дней/раз. Но при отметке они пропадают из списка:
![RocketSim_Recording_iPhone_14_Pro_2023-03-22_22 56 31](https://user-images.githubusercontent.com/121577115/227042924-8cc73955-1542-4ade-bb21-a2695958c91d.gif)
При этом с новой сессией они снова возвращаются, но счетчик неверный (магия)
3. Поиск как работает тоже не ясно: ввожу название категории / привычки – ничего в списке не появляется. 

Приложение выглядит сломанным, надо доработать.

2023-03-22 21:37 UTC, IBDesignable commented on Tracker/Scenes/Category/CategoryCreationViewController.swift
> +    private let labelView: UILabel = UILabel();
```suggestion
    private let labelView: UILabel = UILabel()
```

2023-03-22 21:37 UTC, IBDesignable commented on Tracker/Scenes/Category/CategoryCreationViewController.swift
> +        completion(newCategory)
а зачем понадобилось и делегата и комплишен использовать?

2023-03-22 21:37 UTC, IBDesignable commented on Tracker/Scenes/Category/CategoryViewController.swift
> +        )
Тернарники конечно весело, но этот код совершенно не читаемый :)

2023-03-22 21:37 UTC, IBDesignable commented on Tracker/Scenes/Tracker/TrackerCreationViewController.swift
> +        if isScheduleOK && isInputOK && isCategoryOk && isEmojiOk && isColorOk {
Очень хорошо что назвал каждую проверку отдельным именем - так уже понятно назначение, но можно еще дотянуть так 
let isEnabledContinue = isScheduleOK && isInputOK && isCategoryOk && isEmojiOk && isColorOk 

ну или что-то в этом роде.

2023-03-22 21:37 UTC, IBDesignable commented on Tracker/Scenes/Trackers/TrackersViewController.swift
>          }
Назначение оператора guard - предотвращать нежелательные ситуации. Здесь же блок элз настолько разбух, что уже выглядит как полноценный участок кода. 

Когда так происходит надо заменять гвард на обычный if-else

2023-03-22 21:37 UTC, IBDesignable commented on Tracker/Store/Store.swift
> +        try! self.init(context: context)
```swif
guard let appDelegate = UIApplication.shared.delegate as? AppDelegate else {
   preconditionFailure("Something went terribly wrong")
}

self.context = appDelegate.persistentContainer.viewContext
```
Возможно так же у тебя получится написать init без овверайдов?

2023-03-22 21:37 UTC, IBDesignable commented on Tracker/Store/Store.swift
> +                result.append(TrackerCategory(id: currentCategory.id, label: currentCategory.label, trackers: trackersCD.filter { $0.category!.id == currentCategory.id }.compactMap{ Tracker.fromCoreD
так а если категории случайно не кажется у трекера, упадем получается? Может такое теоретически произойти?

2023-03-22 21:37 UTC, IBDesignable commented on Tracker/Store/TrackerCategoryStore.swift
> +        let categoriesCD = try! context.fetch(request)
Сергей, ну давай хотя бы пытаться писать безопасный код!

Ну не получилось зафетчить, ну верни пустой массив или хотя бы обработай ошибку.

2023-03-22 21:37 UTC, IBDesignable commented on Tracker/Tracker.xcdatamodeld/Tracker.xcdatamodel/contents
> +        <attribute name="label" optional="YES" attributeType="String"/>
Кажется ни одно из этих полей не может быть опциональным

2023-03-22 21:37 UTC, IBDesignable commented on Tracker/Tracker.xcdatamodeld/Tracker.xcdatamodel/contents
> +        <attribute name="label" optional="YES" attributeType="String"/>
Я бы рекомендовала тоже подумать стоит ли здесь оствлять опциональные поля

2023-03-22 21:37 UTC, IBDesignable commented on Tracker/Store/TrackerCategoryStore.swift
> +    }
Я не очень поняла твою задумку, почему у тебя на каждую сущность по новому стору.

Здесь не должно было быть CoreData, все взаимодействие с ее объектами должно было быть сделано через Store.
То есть Store - зависимость TrackerCategoryStore, а не наоборот. 

Все "мясо" обычно упаковывают в некоторое ядро приложения, пишут максимально обобщенный и переиспользуемый код, который не знает о существовании внешнего мира приложения. Например вы так реализовывали сервисный слой запросов в предыдущем модуле.
А остальные сервисы – более высокоуровневые, должны были общаться с ядром.

2023-03-28 22:54 UTC, snowsergo commented on Tracker/Scenes/Category/CategoryCreationViewController.swift
> +    private let labelView: UILabel = UILabel();
Сделал отображение категорий при добавлении, убрал сокрытие трекера, добавил галку о выполнении и количество дней раз. Поиск работает, не совсем понимаю что там чинить. То что мы видим на экране это не пустые категории с учетом текстового поиска и выбранной даты, если в категории нет трекеров имя которых совпадает с текстовым поиском и расписание которых совпадает с выбранной датой то ничего и не отображается, если есть трекеры расписание которых бьется с выбранной датой и текстовым поиском то мы их видим

2023-03-30 21:21 UTC, snowsergo commented on Tracker/Scenes/Category/CategoryCreationViewController.swift
> +        completion(newCategory)
через делегат делается добавление в стор категории, в комплишне добавление категории в список категоий на предыдущем экране выбора категорий

2023-04-02 09:31 UTC, IBDesignable commented on Tracker/Scenes/Category/CategoryCreationViewController.swift
> +    private let labelView: UILabel = UILabel();
Я ввожу текст - название категории и название трекера – в результате поиска пустой экран. Ожидаемо увидеть карточку, название категории или привычки, совпадает со строкой которую я ввожу. 

![RocketSim_Recording_iPhone_14_Pro_Max_2023-04-02_12 28 21](https://user-images.githubusercontent.com/121577115/229344542-c46fabf0-624e-4565-a2bb-690e61a57200.gif)

2023-04-02 09:36 UTC, IBDesignable commented on Tracker/Scenes/Category/CategoryCreationViewController.swift
> +    private let labelView: UILabel = UILabel();
Когда привычка выполнена надо показать галочку
<img width="511" alt="Снимок экрана 2023-04-02 в 12 34 08" src="https://user-images.githubusercontent.com/121577115/229344708-bc8a9023-4baf-4532-9b07-b8afe2579b50.png">

https://www.figma.com/file/owAO4CAPTJdpM1BZU5JHv7/Tracker-(YP)?node-id=36-13319&t=le6kBuLSGZqPs61u-4

2023-04-02 09:47 UTC, IBDesignable approved these changes

2023-04-02 09:47 UTC, IBDesignable commented on Tracker/Helpers/Declination.swift
> +}
Это задача плюрализации строк: когда ты от числительного должен поставить грамматически верный текст.
В данном случае у тебя вероятно верное решение для русского языка: это решение еще хорошо бы протестировать – функция чистая же, легко подвергается тестированию. 

Если бы мы разрабатывали приложение на английском языке – пришлось бы писать новую функцию. 
К счастью у Apple есть специальный инструмент, чтобы такой код не надо было писать!
Для этого придется разобраться с форматом файла Localizable.strigsdict,  собирать строчку по ключу из этого файла, подставляя в нее правильное число (`String.localizedStringWithFormat(key, count)`)

https://medium.com/@vitaliikuznetsov/plurals-localization-using-stringsdict-in-ios-a910aab8c28c  - если будет интересно, можно избавиться от этого алгоритма

2023-04-02 09:47 UTC, IBDesignable commented on Tracker/Scenes/Category/CategoryCreationViewController.swift
>          }
тут можно вынести логическое свойство в константу, и тогда можно будет переписать без использования иф-елса

2023-04-02 09:47 UTC, IBDesignable commented on Tracker/Scenes/Trackers/TrackersViewController.swift
> +        if isCompleted == true {
if isCompleted – короче вариант

2023-04-15 16:46 UTC, merged